apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  clusterIP: None
  selector:
    app: {{ .Values.mysql.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}-read
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: {{ .Values.mysql.name }}
  type: ClusterIP
