apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Values.namespace | default "prod" }}
data:
  my.cnf: |
    [mysqld]
    default-authentication-plugin=mysql_native_password
    max_connections=100
    innodb_buffer_pool_size=64M
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
