# Development environment

namespace: dev
environment: dev

replicas: 1

image:
  repository: ghcr.io/brucekwok5-star/helloword
  tag: 98008b1

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/actuator/prometheus"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: NodePort
  nodePort: 30080
