# Production environment

namespace: prod
environment: prod

replicas: 1

image:
  tag: 1.0.0

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  type: LoadBalancer

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
